image_settings:
  default_directory: ~/Pictures/Screenshots
  filename_pattern: "Screen*.png"

preview_settings:
  max_width: 1000
  max_height: 800

ollama:
  base_url: http://localhost:11434/api/generate
  models:
    - llama3.2-vision
    - gemma3:4b
  max_width: 1200
  max_height: 1200


