#!/bin/bash

DIR=`dirname "$0"`
KITTY="/usr/bin/kitty"
APP="$DIR/env/bin/screenshot-ocr"

if [ ! -x "$KITTY" ]  ; then
	echo "kitty not found"
	exit 1
fi
if [ ! -f "$APP" ] ; then
	echo "script not found"
	exit 1
fi

exec "$KITTY" -e "$APP"
