#!/bin/bash

DIR=`dirname "$0"`
PYTHON="$DIR/env/bin/python3" 
KITTY="/usr/bin/kitty"
APP="$DIR/screenshot_ocr.py"

if [ ! -x "$PYTHON" ]  ; then
	echo "venv not found"
	exit 1
fi
if [ ! -x "$KITTY" ]  ; then
	echo "kitty not found"
	exit 1
fi
if [ ! -f "$APP" ] ; then
	echo "script not found"
	exit 1
fi

exec "$KITTY" -e "$PYTHON" "$APP"
